import "bootstrap/dist/css/bootstrap.css";
import Navbar from "@/components/navbar/navbar";
import Footer from "@/components/footer/footer";
import { Montserrat } from "next/font/google";
import BootstrapClient from "@/components/bootstrap/bootstrapClient";
import "./globals.css";
import ThemeProvider from "@/context/themeContext";
const bodyFont = Montserrat({
  subsets: ["latin"],
  weight: ["900", "700", "400"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${bodyFont.className}`}>
        <ThemeProvider>
          <Navbar />
          {children}
          <Footer />
        </ThemeProvider>
        <BootstrapClient />
      </body>
    </html>
  );
}
